### PR TITLE
Vendorize dependencies using govend

### PR DESCRIPTION
**Pull request by cce**
Use vendored dependencies for protobuf, grpc, pkg/errors, and bson by running:
```
govend -v -l github.com/golang/protobuf/proto github.com/pkg/errors google.golang.org/grpc google.golang.org/grpc/credentials gopkg.in/mgo.v2/bson
```

### CODE REVIEW

**Comment by cce** [comment]
Manually verified that this PR successfully removes library dependency requirements from the sample app:
```
~/freshgo/src/github.com/appoptics/appoptics-apm-go/examples/sample_app$ go build
../../v1/ao/internal/reporter/collector/collector.pb.go:21:8: cannot find package "github.com/golang/protobuf/proto" in any of:
	/usr/local/go/src/github.com/golang/protobuf/proto (from $GOROOT)
	/Users/cce/freshgo/src/github.com/golang/protobuf/proto (from $GOPATH)
../../v1/ao/internal/hdrhist/decode.go:10:2: cannot find package "github.com/pkg/errors" in any of:
	/usr/local/go/src/github.com/pkg/errors (from $GOROOT)
	/Users/cce/freshgo/src/github.com/pkg/errors (from $GOPATH)
../../v1/ao/internal/reporter/collector/collector.pb.go:26:2: cannot find package "golang.org/x/net/context" in any of:
	/usr/local/go/src/golang.org/x/net/context (from $GOROOT)
	/Users/cce/freshgo/src/golang.org/x/net/context (from $GOPATH)
../../v1/ao/internal/reporter/collector/collector.pb.go:27:2: cannot find package "google.golang.org/grpc" in any of:
	/usr/local/go/src/google.golang.org/grpc (from $GOROOT)
	/Users/cce/freshgo/src/google.golang.org/grpc (from $GOPATH)
../../v1/ao/internal/reporter/reporter_grpc.go:21:2: cannot find package "google.golang.org/grpc/credentials" in any of:
	/usr/local/go/src/google.golang.org/grpc/credentials (from $GOROOT)
	/Users/cce/freshgo/src/google.golang.org/grpc/credentials (from $GOPATH)
../../v1/ao/internal/reporter/utils.go:18:2: cannot find package "gopkg.in/mgo.v2/bson" in any of:
	/usr/local/go/src/gopkg.in/mgo.v2/bson (from $GOROOT)
	/Users/cce/freshgo/src/gopkg.in/mgo.v2/bson (from $GOPATH)

~/freshgo/src/github.com/appoptics/appoptics-apm-go/examples/sample_app$ git co vendorize
Switched to branch 'vendorize'
Your branch is up-to-date with 'origin/vendorize'.

~/freshgo/src/github.com/appoptics/appoptics-apm-go/examples/sample_app$ go build
~/freshgo/src/github.com/appoptics/appoptics-apm-go/examples/sample_app$ ls
Dockerfile  main.go  sample_app*
~/freshgo/src/github.com/appoptics/appoptics-apm-go/examples/sample_app$
```

**Comment by tillberg** [comment]
@cce I hit https://github.com/grpc/grpc-go/issues/566 when I tried this branch, and I think anyone else that already imports their own copy of `google.golang.org/grpc` also will. The underlying issue is actually in `golang.org/x/net/trace`, which is incompatible with being vendored and imported twice, though I can't find an issue already filed for it in the main golang issue tracker.

The workaround isn't too tricky, though it's a little messy: users that hit that issue could just delete this vendored copy of grpc and use their own.

**Comment by cce** [comment]
That's too bad — I was hoping to avoid issues with customers that have `grpc.SupportPackageIsVersion3` set in their own gRPC and we are using `grpc.SupportPackageIsVersion4`. What if we just removed golang.org/x/net/trace from our vendor?

**Comment by cce** [comment]
I no longer think this is a good idea — closing.

**Pull request closed without merging**
