### PR TITLE
AO-9930: remove noboe

### PR DESCRIPTION
**Pull request by jiwen624**
**Keep it open until we make sure `noboe` and `disable_tracing` can be removed or not**

Ref: https://swicloud.atlassian.net/browse/AO-9930
`noboe` was originally introduced in Traceview where an oboe library written in C is used as the foundation of the agent. It is a build option to let customers opt out from tracing when the library is not there.

Now as Go has implemented its own reporter and event encoding. `noboe` seems to be not needed any more.

### CODE REVIEW

**Comment by jiwen624** [comment]
Currently we have the `disable agent` flag which disables the agent, mostly the same as `noboe`:
https://github.com/appoptics/appoptics-apm-go/pull/68
https://github.com/appoptics/appoptics-apm-go/pull/77

**Comment by cce** [comment]
The goal of the `disable_tracing` build tag was to ensure that you were going to have zero overhead due to importing the AO library — I'm not sure the `disable_agent` flag does the same thing exactly, does it?

**Comment by cce** [comment]
Or does it? APPOPTICS_DISABLED ensures you always get a nullTrace and a nullReporter, is that enough?

**Comment by cce** [comment]
Reviewing #68 and #77 I think the current handling of APPOPTICS_DISABLED is enough.

**Comment by cce** [comment]
However the README currently mentions the build tag and needs to be replaced with instructions on how to use APPOPTICS_DISABLED instead: https://github.com/appoptics/appoptics-apm-go#building-your-app-with-or-without-tracing

**Comment by jiwen624** [comment]
> However the README currently mentions the build tag and needs to be replaced with instructions on how to use APPOPTICS_DISABLED instead: https://github.com/appoptics/appoptics-apm-go#building-your-app-with-or-without-tracing

Updated the README for the build tag change. I'll double check the tag and make sure nobody is relying on it before making any real changes to noboe.

**Comment by jiwen624** [comment]
Thanks! @cce I'll merge it.

**Pull request merged**
